### ISSUE TITLE
安装成功后，找不到指令

### ISSUE THREAD

**Issue by JinjunHan** [ymoyao/cocoapods-privacy#3]
% pod privacy config https://raw.githubusercontent.com/ymoyao/cocoapods-privacy/main/resources/config.json
[!] Unknown command: `privacy`

好不容易升级了 Ruby 后安装
% sudo gem install cocoapods-privacy
Password:
Fetching cocoapods-privacy-0.5.0.gem
Successfully installed cocoapods-privacy-0.5.0
Parsing documentation for cocoapods-privacy-0.5.0
Installing ri documentation for cocoapods-privacy-0.5.0
Done installing documentation for cocoapods-privacy after 3 seconds
1 gem installed

**Comment by ymoyao** [comment]
> % pod privacy config https://raw.githubusercontent.com/ymoyao/cocoapods-privacy/main/resources/config.json [!] Unknown command: `privacy`
> 
> 好不容易升级了 Ruby 后安装 % sudo gem install cocoapods-privacy Password: Fetching cocoapods-privacy-0.5.0.gem Successfully installed cocoapods-privacy-0.5.0 Parsing documentation for cocoapods-privacy-0.5.0 Installing ri documentation for cocoapods-privacy-0.5.0 Done installing documentation for cocoapods-privacy after 3 seconds 1 gem installed

这个应该是环境问题，有多种情况可能导致，这里说明下常见的两种：
第一种：如果你使用Gemfile 来控制工程局部插件环境，那么需要在Gemfile 添加 gem "cocoapods-privacy", ">= 0.5.0",执行bundle install 后重启终端再尝试
第二种：新增gem/ruby 路径配置有问题 
这里假设你是通过 homebrew 来安装的ruby3.2 和 gem，并使用zsh 来管理，那么可以在～/.zshrc 文件末尾添加下面命令后重启终端再尝试（其他版本类似操作）
export PATH="/opt/homebrew/opt/ruby@3.2/bin:$PATH"
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export PATH="/opt/homebrew/lib/ruby/gems/3.2.0/bin:$PATH"

**Comment by JinjunHan** [comment]
我也感觉是 ruby 问题，最终装了 rvm 去管理就行了，真不太会搞配置环境这些东西
