### ISSUE TITLE
点击“生成隐私报告”按钮时,不会显示第三方 SDK 的隐私报告

### ISSUE THREAD

**Issue by wcsdn** [ymoyao/cocoapods-privacy#5]
如上，这是什么原因？
![image](https://github.com/ymoyao/cocoapods-privacy/assets/10184993/c308d7e8-43e1-49d4-8b8b-c69dfb37cee2)

![image](https://github.com/ymoyao/cocoapods-privacy/assets/10184993/faa79984-8277-4521-ab7b-ade600fa3e66)

**Comment by wcsdn** [comment]
@ymoyao  大佬，这是什么原因，回复一下 ，xcode 15.2

**Comment by ymoyao** [comment]
> 如上，这是什么原因？ ![image](https://private-user-images.githubusercontent.com/10184993/318007433-c308d7e8-43e1-49d4-8b8b-c69dfb37cee2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMjA0NjcsIm5iZiI6MTcxMjAyMDE2NywicGF0aCI6Ii8xMDE4NDk5My8zMTgwMDc0MzMtYzMwOGQ3ZTgtNDNlMS00OWQ0LThiOGItYzY5ZGZiMzdjZWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDAxMDkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZmRkYTY2YTIwYWVkNTUzOWEzMjYwZmQ4ZDIyNjZkMGQ2ZmY5MGNmN2YyOWY2NTdlMTEwMWJmODU5NDYxNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P1ftX_as-7uM2aouTxyqndLNhf_auvyLmoRvrpFZlik)
> 
> ![image](https://private-user-images.githubusercontent.com/10184993/318007586-faa79984-8277-4521-ab7b-ade600fa3e66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMjA0NjcsIm5iZiI6MTcxMjAyMDE2NywicGF0aCI6Ii8xMDE4NDk5My8zMTgwMDc1ODYtZmFhNzk5ODQtODI3Ny00NTIxLWFiN2ItYWRlNjAwZmEzZTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDAxMDkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MTU2MDczOTM3NjBiMDM4ZGY5NDY2YWFhMDEzM2JiZTU3MzFlZTQwYWRmMDg5NTc3MTc2OWUxYzg1NDVjMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O2kLgti-MfE7eMsl4BpHoqxOpbFq0cy6d2_5WNQzuz4)

这是正常的，只有隐私数据才会出现在这份报告中，主要为了提醒用户app使用了哪些隐私数据和隐私权限！而隐私api不会出现在隐私报告里面，隐私api对接的是苹果官方，苹果想知道你用了哪些他们不推荐的api。

**Comment by wcsdn** [comment]
> 主要为了提醒用户app使用了哪

不应该啊，我用这个大佬的方式检测出一堆呢。https://juejin.cn/post/7329732000087425064
尤其是flutter 里的隐私文件，明确加了几条，并且也在framework里。但是生成的时候依旧没有。
主项目 生产的隐私文件里的条目也不显示在这个pdf里吗？我主项目的隐私文件也不少内容呢。奇怪了。

**Comment by KeWangKW** [comment]
我试了一下，这个pdf只显示 Privacy Nutrition Label Types 的内容

**Comment by wcsdn** [comment]
> 我试了一下，这个pdf只显示 Privacy Nutrition Label Types 的内容

大哥，你是对的。
