### ISSUE TITLE
Encoding::CompatibilityError - invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by LW0NG** [ymoyao/cocoapods-privacy#7]
```
Encoding::CompatibilityError - invalid byte sequence in UTF-8
/Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:214:in `strip'
/Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:214:in `block in contains_apis_ignore_line_comment'
/Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:213:in `each'
/Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:213:in `contains_apis_ignore_line_comment'
/Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:203:in `contains_apis?'
/Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:340:in `block in search_files'
/Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:339:in `each'
/Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:339:in `each_with_index'
/Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:339:in `search_files'
/Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:44:in `search_pricacy_apis'
/Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyModule.rb:240:in `load_project'
/Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/privacy_installer_hook.rb:135:in `privacy_handle'
/Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/privacy_installer_hook.rb:72:in `install!'
/Users/xxx/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:52:in `run'
/Users/xxx/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/xxx/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/Users/xxx/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/Users/xxx/.rvm/rubies/ruby-3.3.0/bin/pod:25:in `load'
/Users/xxx/.rvm/rubies/ruby-3.3.0/bin/pod:25:in `<main>'
/Users/xxx/.rvm/gems/ruby-3.3.0/bin/ruby_executable_hooks:22:in `eval'
/Users/xxx/.rvm/gems/ruby-3.3.0/bin/ruby_executable_hooks:22:in `<main>'

**Comment by ymoyao** [comment]
> ```
> Encoding::CompatibilityError - invalid byte sequence in UTF-8
> /Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:214:in `strip'
> /Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:214:in `block in contains_apis_ignore_line_comment'
> /Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:213:in `each'
> /Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:213:in `contains_apis_ignore_line_comment'
> /Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:203:in `contains_apis?'
> /Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:340:in `block in search_files'
> /Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:339:in `each'
> /Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:339:in `each_with_index'
> /Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:339:in `search_files'
> /Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:44:in `search_pricacy_apis'
> /Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/PrivacyModule.rb:240:in `load_project'
> /Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/privacy_installer_hook.rb:135:in `privacy_handle'
> /Users/xxx/.rvm/gems/ruby-3.3.0/gems/cocoapods-privacy-0.5.1/lib/cocoapods-privacy/privacy/privacy_installer_hook.rb:72:in `install!'
> /Users/xxx/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:52:in `run'
> /Users/xxx/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
> /Users/xxx/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
> /Users/xxx/.rvm/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
> /Users/xxx/.rvm/rubies/ruby-3.3.0/bin/pod:25:in `load'
> /Users/xxx/.rvm/rubies/ruby-3.3.0/bin/pod:25:in `<main>'
> /Users/xxx/.rvm/gems/ruby-3.3.0/bin/ruby_executable_hooks:22:in `eval'
> /Users/xxx/.rvm/gems/ruby-3.3.0/bin/ruby_executable_hooks:22:in `<main>'
> ```

Is there a special file format? Not included in ['.m', '.c', '.swift', '.mm', '.h', '.hap', '.hpp', '.cpp'] Format， you can post it after code desensitization

**Comment by ymoyao** [comment]
fix in 0.5.2 version

**Comment by caihongyu2022** [comment]
@ymoyao  0.5.2 version 执行 pod privacy install 问题依旧
```
ArgumentError - invalid byte sequence in UTF-8
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:228:in `strip'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:228:in `block in contains_apis_ignore_line_comment'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:227:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:227:in `contains_apis_ignore_line_comment'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:217:in `contains_apis?'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:354:in `block in search_files'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:353:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:353:in `each_with_index'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:353:in `search_files'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:44:in `search_pricacy_apis'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyModule.rb:240:in `load_project'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/privacy_installer_hook.rb:135:in `privacy_handle'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/privacy_installer_hook.rb:60:in `privacy_analysis'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/command/privacy/install.rb:39:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.13.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.13.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:25:in `load'
/usr/local/bin/pod:25:in `<main>'
```

**Comment by WsmGitHub** [comment]
Encoding::CompatibilityError - invalid byte sequence in UTF-8
/Users/wsm/.rvm/gems/ruby-2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:259:in `strip'
/Users/wsm/.rvm/gems/ruby-2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:259:in `block in contains_apis_ignore_all_comment'
/Users/wsm/.rvm/gems/ruby-2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:258:in `each'
/Users/wsm/.rvm/gems/ruby-2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:258:in `contains_apis_ignore_all_comment'
/Users/wsm/.rvm/gems/ruby-2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:218:in `contains_apis?'
/Users/wsm/.rvm/gems/ruby-2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:358:in `block in search_files'
/Users/wsm/.rvm/gems/ruby-2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:357:in `each'
/Users/wsm/.rvm/gems/ruby-2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:357:in `each_with_index'
/Users/wsm/.rvm/gems/ruby-2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:357:in `search_files'
/Users/wsm/.rvm/gems/ruby-2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyHunter.rb:44:in `search_pricacy_apis'
/Users/wsm/.rvm/gems/ruby-2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/PrivacyModule.rb:240:in `load_project'
/Users/wsm/.rvm/gems/ruby-2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/privacy_installer_hook.rb:135:in `privacy_handle'
/Users/wsm/.rvm/gems/ruby-2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/privacy/privacy_installer_hook.rb:60:in `privacy_analysis'
/Users/wsm/.rvm/gems/ruby-2.7.0/gems/cocoapods-privacy-0.5.2/lib/cocoapods-privacy/command/privacy/install.rb:39:in `run'


============================================================================================

我的0.5.2也有这个问题

**Comment by caihongyu2022** [comment]
@ymoyao  0.5.2 gem包中的PrivacyHunter.rb 的方法self.contains_apis中的下面的代码有问题吧

file_content = File.read(file_path, encoding: 'UTF-8', invalid: :replace, undef: :replace)  这句代码当项目中存在非utf-8的文件时(例如:字体.ttf,音频，视频文件)是不是会导致因编码问题，无法读取文件，导致命令异常无法继续执行呢？

在读取文件之前是不是要对file_path 加上 例如 这句代码的文件扩展名的判断 ？ need_check_paragraph_comment = ['.m', '.c', '.swift', '.mm', '.h', '.hap', '.hpp', '.cpp'].include?(file_extension)

```
def self.contains_apis?(file_path, apis)

      #使用UTF-8 读取，无法读取的会被默认处理，修复 https://github.com/ymoyao/cocoapods-privacy/issues/7 
      file_content = File.read(file_path, encoding: 'UTF-8', invalid: :replace, undef: :replace)

      #核心文件检查段落注释 /* */
      file_extension = File.extname(file_path).downcase
      need_check_paragraph_comment = ['.m', '.c', '.swift', '.mm', '.h', '.hap', '.hpp', '.cpp'].include?(file_extension)

      if need_check_paragraph_comment 
        # 计算段注释 /**/
        apis_found = contains_apis_ignore_all_comment(file_content.lines,apis)
      else
        # 计算单独行注释 //
        apis_found = contains_apis_ignore_line_comment(file_content.lines,apis)
      end
      apis_found
    end

```

**Comment by WsmGitHub** [comment]
已找到问题原因，并解决
原因：文件包含特殊字符，File.read 出来的特殊字符丢失部分格式，导致变成非utf8编码，在使用line.strip 时导致异常

解决方案：
PrivacyHunter文件中修改 
 # 可能是特殊字符，先去掉特殊字符
        lineValue = line.scrub("")
          
        next if lineValue.strip.empty? #忽略空行
        next if lineValue.strip.start_with?('//') #忽略单行

**Comment by caihongyu2022** [comment]
> 已找到问题原因，并解决 原因：文件包含特殊字符，File.read 出来的特殊字符丢失部分编码，导致变成非utf8编码，在使用line.strip 时导致异常
> 
> 解决方案： PrivacyHunter文件中修改
> 
> # 可能是特殊字符，先去掉特殊字符
> ```
>     lineValue = line.scrub("")
>       
>     next if lineValue.strip.empty? #忽略空行
>     next if lineValue.strip.start_with?('//') #忽略单行
> ```

是的，通过添加line = line.srub("")  确实解决了utf-8编码问题。 如果着急使用，作者没及时修改的情况下，可以下载作者的源码，修改PrivacyHunter 文件，然后本地通过 gem build 命令生成gem包，然后通过 gem install 安装

`analyzing dependencies
👇👇👇👇👇👇 Start analysis project privacy 👇👇👇👇👇👇
{"NSPrivacyAccessedAPIType"=>"NSPrivacyAccessedAPICategoryUserDefaults", "NSPrivacyAccessedAPITypeReasons"=>["CA92.1"]}
{"NSPrivacyAccessedAPIType"=>"NSPrivacyAccessedAPICategoryFileTimestamp", "NSPrivacyAccessedAPITypeReasons"=>["C617.1"]}
{"NSPrivacyAccessedAPIType"=>"NSPrivacyAccessedAPICategoryDiskSpace", "NSPrivacyAccessedAPITypeReasons"=>["E174.1", "85F4.1"]}
{"NSPrivacyAccessedAPIType"=>"NSPrivacyAccessedAPICategorySystemBootTime", "NSPrivacyAccessedAPITypeReasons"=>["35F9.1"]}
xxxx/Resources/PrivacyInfo.xcprivacy 数据一致，无需插入。
详细log请查看 /Users/xxx/.cache/cocoapods-privacy/privacy/privacy.log 文件
👆👆👆👆👆👆 End analysis project privacy 👆👆👆👆👆👆`

**Comment by ymoyao** [comment]
@caihongyu2022 @LW0NG @WsmGitHub   这个问题在 0.5.3 版本中已修复，你们的特殊字符文件如果方便的话可以发一份出来我做个数据参考～

**Comment by WsmGitHub** [comment]
> @caihongyu2022 @LW0NG @WsmGitHub 这个问题在 0.5.3 版本中已修复，你们的特殊字符文件如果方便的话可以发一份出来我做个数据参考～

//ensure gain £°=0 这个注释读取出来丢失了部分编码，直接复制过去没问题
